In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("uiuc_demographics_2005_15.csv")

In [3]:
df

,Fall,Term Code,College,Dept.,Degree,Major Code,Major Name,Conc. Code,Conc. Name,Total,Male,Female,Unknown,Academic Program Code
0,2015.0,120158.0,KP,227.0,BS,5163.0,Agricultural & Biological Engr,5270,Agricultural Engineering,17.0,14.0,3.0,0.0,10KP5163BS
1,2015.0,120158.0,KP,227.0,BS,5163.0,Agricultural & Biological Engr,5271,Biological Engineering,15.0,11.0,4.0,0.0,10KP5163BS
2,2015.0,120158.0,KP,227.0,MENGR,1211.0,Engineering,5370,Energy Systems,20.0,14.0,6.0,0.0,10KS5370MENG
3,2015.0,120158.0,KP,227.0,BS,5163.0,Agricultural & Biological Engr,,,31.0,22.0,9.0,0.0,10KP5163BS
4,2015.0,120158.0,KP,227.0,MS,5163.0,Agricultural & Biological Engr,,,29.0,20.0,9.0,0.0,10KS5163MS
5,2015.0,120158.0,KP,227.0,PHD,5163.0,Agricultural & Biological Engr,,,34.0,21.0,13.0,0.0,10KS5163PHD
6,2015.0,120158.0,KP,227.0,NDEG,67.0,Nondegree,,,218.0,172.0,46.0,0.0,10KP0067NDEG
7,2015.0,120158.0,KM,230.0,MBA,9875.0,Business Administration (MBA),5469,Info Technology and Control,1.0,1.0,0.0,0.0,10KS9875MBA
8,2015.0,120158.0,KM,230.0,MBA,9875.0,Business Administration (MBA),4064,MBA,104.0,71.0,33.0,0.0,10KS4064MBA
9,2015.0,120158.0,KM,230.0,MBA,9875.0,Business Administration (MBA),,,154.0,112.0,42.0,0.0,10KS9875MBA
10,2015.0,120158.0,KT,238.0,PHD,279.0,Communications,,,6.0,2.0,4.0,0.0,10KS0279PHD
11,2015.0,120158.0,KT,238.0,PHD,5202.0,Communications and Media,,,40.0,13.0,27.0,0.0,10KS5202PHD
12,2015.0,120158.0,KV,241.0,BALAS,340.0,Anthropology,5043,Socioculturl & Linguistic Anth,3.0,2.0,1.0,0.0,10KV5043BALA
13,2015.0,120158.0,KV,241.0,BALAS,340.0,Anthropology,,,7.0,1.0,6.0,0.0,10KV8037BALA
14,2015.0,120158.0,KV,241.0,BSLAS,5348.0,Computer Sci & Anthropology,,,1.0,0.0,1.0,0.0,10KV8037BSLA
15,2015.0,120158.0,KV,241.0,BSLAS,5348.0,Computer Sci & Anthropology,,,10.0,8.0,2.0,0.0,10KV5348BSLA
16,2015.0,120158.0,KV,241.0,BALAS,340.0,Anthropology,,,75.0,24.0,51.0,0.0,10KV0340BALA
17,2015.0,120158.0,KV,241.0,PHD,340.0,Anthropology,,,61.0,16.0,45.0,0.0,10KS0340PHD
18,2015.0,120158.0,KP,244.0,MS,240.0,Physics,,,3.0,3.0,0.0,0.0,10KS0240MS
19,2015.0,120158.0,KP,244.0,BS,121.0,Engineering Physics,,,248.0,218.0,30.0,0.0,10KP0121BS
20,2015.0,120158.0,KP,244.0,PHD,240.0,Physics,,,258.0,200.0,58.0,0.0,10KS0240PHD
21,2015.0,120158.0,KP,251.0,PHD,232.0,Environ Science in Civil Engr,,,1.0,0.0,1.0,0.0,10KS0232PHD
22,2015.0,120158.0,KP,251.0,MS,106.0,Civil Engineering,,,2.0,2.0,0.0,0.0,10KS0106MSU
23,2015.0,120158.0,KP,251.0,PHD,231.0,Environ Engr in Civil Engr,,,45.0,23.0,22.0,0.0,10KS0231PHD
24,2015.0,120158.0,KP,251.0,MS,231.0,Environ Engr in Civil Engr,,,55.0,23.0,32.0,0.0,10KS0231MS
25,2015.0,120158.0,KP,251.0,PHD,106.0,Civil Engineering,,,190.0,148.0,42.0,0.0,10KS0106PHD
26,2015.0,120158.0,KP,251.0,BS,106.0,Civil Engineering,,,730.0,536.0,194.0,0.0,10KP0106BS
27,2015.0,120158.0,KP,251.0,MS,106.0,Civil Engineering,,,397.0,290.0,107.0,0.0,10KS0106MS
28,2015.0,120158.0,KV,253.0,BSLAS,334.0,Atmospheric Sciences,,,3.0,2.0,1.0,0.0,10KV8037BSLA
29,2015.0,120158.0,KV,253.0,BSLAS,334.0,Atmospheric Sciences,,,62.0,34.0,28.0,0.0,10KV0334BSLA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7298,2005.0,120058.0,KV,985.0,BALAS,304.0,French,3875,French Commercial Studies,7.0,3.0,4.0,0.0,10KV3875BALA
7299,2005.0,120058.0,KV,985.0,BA,295.0,Teaching of French,,,8.0,2.0,6.0,0.0,10KV0295BA
7300,2005.0,120058.0,KV,985.0,BALAS,304.0,French,3876,French Studies,3.0,0.0,3.0,0.0,10KV3876BALA
7301,2005.0,120058.0,KV,985.0,NDEG,304.0,French,,,5.0,3.0,2.0,0.0,10KS0304NDEG
7302,2005.0,120058.0,KV,985.0,BALAS,304.0,French,,,57.0,14.0,43.0,0.0,10KV0304BALA
7303,2005.0,120058.0,KV,985.0,MA,304.0,French,,,17.0,6.0,11.0,0.0,10KS0304MA
7304,2005.0,120058.0,KV,985.0,PHD,304.0,French,,,13.0,3.0,10.0,0.0,10KS0304PHD
7305,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,,,2.0,1.0,1.0,0.0,10KS0370MSU
7306,2005.0,120058.0,LP,992.0,CAS,370.0,Library & Information Science,,,9.0,0.0,9.0,0.0,10KS0370CAS
7307,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,0372,Library & Info Sci - MS/F,5.0,0.0,5.0,0.0,10KS0372MS
7308,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,0376,Library & Info Sci - Media,13.0,1.0,12.0,0.0,10KS0376MS
7309,2005.0,120058.0,LP,992.0,PHD,370.0,Library & Information Science,,,48.0,17.0,31.0,0.0,10KS0370PHD
7310,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,,,170.0,49.0,121.0,0.0,10KS0370MS
7311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df["% Female"] = df["Female"] / df["Total"]

In [5]:
df

,Fall,Term Code,College,Dept.,Degree,Major Code,Major Name,Conc. Code,Conc. Name,Total,Male,Female,Unknown,Academic Program Code,% Female
0,2015.0,120158.0,KP,227.0,BS,5163.0,Agricultural & Biological Engr,5270,Agricultural Engineering,17.0,14.0,3.0,0.0,10KP5163BS,0.176471
1,2015.0,120158.0,KP,227.0,BS,5163.0,Agricultural & Biological Engr,5271,Biological Engineering,15.0,11.0,4.0,0.0,10KP5163BS,0.266667
2,2015.0,120158.0,KP,227.0,MENGR,1211.0,Engineering,5370,Energy Systems,20.0,14.0,6.0,0.0,10KS5370MENG,0.300000
3,2015.0,120158.0,KP,227.0,BS,5163.0,Agricultural & Biological Engr,,,31.0,22.0,9.0,0.0,10KP5163BS,0.290323
4,2015.0,120158.0,KP,227.0,MS,5163.0,Agricultural & Biological Engr,,,29.0,20.0,9.0,0.0,10KS5163MS,0.310345
5,2015.0,120158.0,KP,227.0,PHD,5163.0,Agricultural & Biological Engr,,,34.0,21.0,13.0,0.0,10KS5163PHD,0.382353
6,2015.0,120158.0,KP,227.0,NDEG,67.0,Nondegree,,,218.0,172.0,46.0,0.0,10KP0067NDEG,0.211009
7,2015.0,120158.0,KM,230.0,MBA,9875.0,Business Administration (MBA),5469,Info Technology and Control,1.0,1.0,0.0,0.0,10KS9875MBA,0.000000
8,2015.0,120158.0,KM,230.0,MBA,9875.0,Business Administration (MBA),4064,MBA,104.0,71.0,33.0,0.0,10KS4064MBA,0.317308
9,2015.0,120158.0,KM,230.0,MBA,9875.0,Business Administration (MBA),,,154.0,112.0,42.0,0.0,10KS9875MBA,0.272727
10,2015.0,120158.0,KT,238.0,PHD,279.0,Communications,,,6.0,2.0,4.0,0.0,10KS0279PHD,0.666667
11,2015.0,120158.0,KT,238.0,PHD,5202.0,Communications and Media,,,40.0,13.0,27.0,0.0,10KS5202PHD,0.675000
12,2015.0,120158.0,KV,241.0,BALAS,340.0,Anthropology,5043,Socioculturl & Linguistic Anth,3.0,2.0,1.0,0.0,10KV5043BALA,0.333333
13,2015.0,120158.0,KV,241.0,BALAS,340.0,Anthropology,,,7.0,1.0,6.0,0.0,10KV8037BALA,0.857143
14,2015.0,120158.0,KV,241.0,BSLAS,5348.0,Computer Sci & Anthropology,,,1.0,0.0,1.0,0.0,10KV8037BSLA,1.000000
15,2015.0,120158.0,KV,241.0,BSLAS,5348.0,Computer Sci & Anthropology,,,10.0,8.0,2.0,0.0,10KV5348BSLA,0.200000
16,2015.0,120158.0,KV,241.0,BALAS,340.0,Anthropology,,,75.0,24.0,51.0,0.0,10KV0340BALA,0.680000
17,2015.0,120158.0,KV,241.0,PHD,340.0,Anthropology,,,61.0,16.0,45.0,0.0,10KS0340PHD,0.737705
18,2015.0,120158.0,KP,244.0,MS,240.0,Physics,,,3.0,3.0,0.0,0.0,10KS0240MS,0.000000
19,2015.0,120158.0,KP,244.0,BS,121.0,Engineering Physics,,,248.0,218.0,30.0,0.0,10KP0121BS,0.120968
20,2015.0,120158.0,KP,244.0,PHD,240.0,Physics,,,258.0,200.0,58.0,0.0,10KS0240PHD,0.224806
21,2015.0,120158.0,KP,251.0,PHD,232.0,Environ Science in Civil Engr,,,1.0,0.0,1.0,0.0,10KS0232PHD,1.000000
22,2015.0,120158.0,KP,251.0,MS,106.0,Civil Engineering,,,2.0,2.0,0.0,0.0,10KS0106MSU,0.000000
23,2015.0,120158.0,KP,251.0,PHD,231.0,Environ Engr in Civil Engr,,,45.0,23.0,22.0,0.0,10KS0231PHD,0.488889
24,2015.0,120158.0,KP,251.0,MS,231.0,Environ Engr in Civil Engr,,,55.0,23.0,32.0,0.0,10KS0231MS,0.581818
25,2015.0,120158.0,KP,251.0,PHD,106.0,Civil Engineering,,,190.0,148.0,42.0,0.0,10KS0106PHD,0.221053
26,2015.0,120158.0,KP,251.0,BS,106.0,Civil Engineering,,,730.0,536.0,194.0,0.0,10KP0106BS,0.265753
27,2015.0,120158.0,KP,251.0,MS,106.0,Civil Engineering,,,397.0,290.0,107.0,0.0,10KS0106MS,0.269521
28,2015.0,120158.0,KV,253.0,BSLAS,334.0,Atmospheric Sciences,,,3.0,2.0,1.0,0.0,10KV8037BSLA,0.333333
29,2015.0,120158.0,KV,253.0,BSLAS,334.0,Atmospheric Sciences,,,62.0,34.0,28.0,0.0,10KV0334BSLA,0.451613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7298,2005.0,120058.0,KV,985.0,BALAS,304.0,French,3875,French Commercial Studies,7.0,3.0,4.0,0.0,10KV3875BALA,0.571429
7299,2005.0,120058.0,KV,985.0,BA,295.0,Teaching of French,,,8.0,2.0,6.0,0.0,10KV0295BA,0.750000
7300,2005.0,120058.0,KV,985.0,BALAS,304.0,French,3876,French Studies,3.0,0.0,3.0,0.0,10KV3876BALA,1.000000
7301,2005.0,120058.0,KV,985.0,NDEG,304.0,French,,,5.0,3.0,2.0,0.0,10KS0304NDEG,0.400000
7302,2005.0,120058.0,KV,985.0,BALAS,304.0,French,,,57.0,14.0,43.0,0.0,10KV0304BALA,0.754386
7303,2005.0,120058.0,KV,985.0,MA,304.0,French,,,17.0,6.0,11.0,0.0,10KS0304MA,0.647059
7304,2005.0,120058.0,KV,985.0,PHD,304.0,French,,,13.0,3.0,10.0,0.0,10KS0304PHD,0.769231
7305,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,,,2.0,1.0,1.0,0.0,10KS0370MSU,0.500000
7306,2005.0,120058.0,LP,992.0,CAS,370.0,Library & Information Science,,,9.0,0.0,9.0,0.0,10KS0370CAS,1.000000
7307,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,0372,Library & Info Sci - MS/F,5.0,0.0,5.0,0.0,10KS0372MS,1.000000
7308,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,0376,Library & Info Sci - Media,13.0,1.0,12.0,0.0,10KS0376MS,0.923077
7309,2005.0,120058.0,LP,992.0,PHD,370.0,Library & Information Science,,,48.0,17.0,31.0,0.0,10KS0370PHD,0.645833
7310,2005.0,120058.0,LP,992.0,MS,370.0,Library & Information Science,,,170.0,49.0,121.0,0.0,10KS0370MS,0.711765
7311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
group_majors = df.groupby("Major Name")

In [7]:
group_majors

In [8]:
group_majors.describe()

                                        % Female  Dept.         Fall  \
Major Name
Accountancy                     count  71.000000   71.0    71.000000
                                mean    0.504214  346.0  2009.380282
                                std     0.213181    0.0     3.199849
                                min     0.000000  346.0  2005.000000
                                25%     0.421554  346.0  2007.000000
                                50%     0.459893  346.0  2009.000000
                                75%     0.537088  346.0  2012.000000
                                max     1.000000  346.0  2015.000000
Actuarial Science               count  24.000000   24.0    24.000000
                                mean    0.440671  257.0  2010.208333
                                std     0.191762    0.0     3.175712
                                min     0.000000  257.0  2005.000000
                                25%     0.353952  257.0  2007.750000
                                50%     0.419408  257.0  2010.500000
                                75%     0.593878  257.0  2013.000000
                                max     0.750000  257.0  2015.000000
Advertising                     count  22.000000   22.0    22.000000
                                mean    0.743085  408.0  2010.000000
                                std     0.073823    0.0     3.236694
                                min     0.664319  408.0  2005.000000
                                25%     0.700926  408.0  2007.250000
                                50%     0.719971  408.0  2010.000000
                                75%     0.750000  408.0  2012.750000
                                max     1.000000  408.0  2015.000000
Aero & Astro Engineering        count   5.000000    5.0     5.000000
                                mean    0.081478  615.0  2005.600000
                                std     0.097680    0.0     0.547723
                                min     0.000000  615.0  2005.000000
                                25%     0.000000  615.0  2005.000000
                                50%     0.040000  615.0  2006.000000
...                                          ...    ...          ...
VMS-Veterinary Clinical Medcne  std     0.294566    0.0     3.123855
                                min     0.000000  598.0  2005.000000
                                25%     0.600000  598.0  2007.000000
                                50%     0.738017  598.0  2009.000000
                                75%     1.000000  598.0  2012.000000
                                max     1.000000  598.0  2015.000000
Veterinary Medical Science      count   2.000000    2.0     2.000000
                                mean    0.750000  444.0  2006.500000
                                std     0.353553    0.0     0.707107
                                min     0.500000  444.0  2006.000000
                                25%     0.625000  444.0  2006.250000
                                50%     0.750000  444.0  2006.500000
                                75%     0.875000  444.0  2006.750000
                                max     1.000000  444.0  2007.000000
Veterinary Medicine             count  23.000000   23.0    23.000000
                                mean    0.775852  444.0  2010.434783
                                std     0.321428    0.0     2.793273
                                min     0.000000  444.0  2005.000000
                                25%     0.792288  444.0  2008.500000
                                50%     0.823045  444.0  2010.000000
                                75%     1.000000  444.0  2012.500000
                                max     1.000000  444.0  2015.000000
Voice                           count  11.000000   11.0    11.000000
                                mean    0.796763  495.0  2010.000000
                                std     0.027283    0.0     3.316625
                                min     0.750000  495.0  2005.000000
                                25%     0.776190  495.0  2007.500000
                                50%     0.800000  495.0  2010.000000
                                75%     0.811012  495.0  2012.500000
                                max     0.842105  495.0  2015.000000

                                           Female  Major Code        Male  \
Major Name
Accountancy                     count   71.000000        71.0   71.000000
                                mean    96.380282        71.0  103.633803
                                std    134.043955         0.0  162.449046
                                min      0.000000        71.0    0.000000
                                25%      9.500000        71.0   13.000000
                                50%     45.000000        71.0   27.000000
                                75%    112.000000        71.0  100.500000
                                max    490.000000        71.0  533.000000
Actuarial Science               count   24.000000        24.0   24.000000
                                mean    54.541667       461.0   85.125000
                                std     55.206316         0.0   90.079826
                                min      0.000000       461.0    1.000000
                                25%      3.000000       461.0    2.000000
                                50%     26.000000       461.0   17.000000
                                75%    111.250000       461.0  174.000000
                                max    144.000000       461.0  204.000000
Advertising                     count   22.000000        22.0   22.000000
                                mean   178.363636       277.0   73.681818
                                std    171.952802         0.0   75.328099
                                min     12.000000       277.0    0.000000
                                25%     21.000000       277.0    7.250000
                                50%    101.500000       277.0   35.000000
                                75%    341.000000       277.0  154.000000
                                max    434.000000       277.0  193.000000
Aero & Astro Engineering        count    5.000000         5.0    5.000000
                                mean     1.800000        99.0   12.600000
                                std      2.167948         0.0   10.064790
                                min      0.000000        99.0    1.000000
                                25%      0.000000        99.0    3.000000
                                50%      1.000000        99.0   17.000000
...                                           ...         ...         ...
VMS-Veterinary Clinical Medcne  std      8.484441         0.0    3.784879
                                min      0.000000       359.0    0.000000
                                25%      1.000000       359.0    0.000000
                                50%      2.000000       359.0    1.500000
                                75%     15.000000       359.0    6.750000
                                max     29.000000       359.0   11.000000
Veterinary Medical Science      count    2.000000         2.0    2.000000
                                mean     1.000000       356.0    0.500000
                                std      0.000000         0.0    0.707107
                                min      1.000000       356.0    0.000000
                                25%      1.000000       356.0    0.250000
                                50%      1.000000       356.0    0.500000
                                75%      1.000000       356.0    0.750000
                                max      1.000000       356.0    1.000000
Veterinary Medicine             count   23.000000        23.0   23.000000
                                mean   177.826087       480.0   42.565217
                                std    189.932680         0.0   45.575937
                                min      0.000000       480.0    0.000000
                                25%      1.000000       480.0    0.000000
                                50%      3.000000       480.0    1.000000
                                75%    369.500000       480.0   90.500000
                                max    420.000000       480.0   99.000000
Voice                           count   11.000000        11.0   11.000000
                                mean    22.000000       157.0    5.636364
                                std      4.147288         0.0    1.286291
                                min     16.000000       157.0    3.000000
                                25%     19.000000       157.0    5.000000
                                50%     22.000000       157.0    6.000000
                                75%     24.500000       157.0    6.500000
                                max     28.000000       157.0    7.000000

                                           Term Code        Total    Unknown
Major Name
Accountancy                     count      71.000000    71.000000  71.000000
                                mean   120101.802817   200.253521   0.239437
                                std        31.998491   294.818914   0.706395
                                min    120058.000000     1.000000   0.000000
                                25%    120078.000000    22.500000   0.000000
                                50%    120098.000000    80.000000   0.000000
                                75%    120128.000000   193.500000   0.000000
                                max    120158.000000  1023.000000   4.000000
Actuarial Science               count      24.000000    24.000000  24.000000
                                mean   120110.083333   139.708333   0.041667
                                std        31.757117   144.107291   0.204124
                                min    120058.000000     1.000000   0.000000
                                25%    120085.500000     4.000000   0.000000
                                50%    120113.000000    43.000000   0.000000
                                75%    120138.000000   279.500000   0.000000
                                max    120158.000000   348.000000   1.000000
Advertising                     count      22.000000    22.000000  22.000000
                                mean   120108.000000   252.090909   0.045455
                                std        32.366944   246.747781   0.213201
                                min    120058.000000    15.000000   0.000000
                                25%    120080.500000    27.250000   0.000000
                                50%    120108.000000   136.500000   0.000000
                                75%    120135.500000   491.500000   0.000000
                                max    120158.000000   626.000000   1.000000
Aero & Astro Engineering        count       5.000000     5.000000   5.000000
                                mean   120064.000000    14.400000   0.000000
                                std         5.477226    11.480418   0.000000
                                min    120058.000000     1.000000   0.000000
                                25%    120058.000000     3.000000   0.000000
                                50%    120068.000000    20.000000   0.000000
...                                              ...          ...        ...
VMS-Veterinary Clinical Medcne  std        31.238545    11.892155   0.000000
                                min    120058.000000     1.000000   0.000000
                                25%    120078.000000     1.000000   0.000000
                                50%    120098.000000     3.000000   0.000000
                                75%    120128.000000    23.750000   0.000000
                                max    120158.000000    36.000000   0.000000
Veterinary Medical Science      count       2.000000     2.000000   2.000000
                                mean   120073.000000     1.500000   0.000000
                                std         7.071068     0.707107   0.000000
                                min    120068.000000     1.000000   0.000000
                                25%    120070.500000     1.250000   0.000000
                                50%    120073.000000     1.500000   0.000000
                                75%    120075.500000     1.750000   0.000000
                                max    120078.000000     2.000000   0.000000
Veterinary Medicine             count      23.000000    23.000000  23.000000
                                mean   120112.347826   220.826087   0.434783
                                std        27.932726   235.153461   0.727767
                                min    120058.000000     1.000000   0.000000
                                25%    120093.000000     1.000000   0.000000
                                50%    120108.000000     3.000000   0.000000
                                75%    120133.000000   466.000000   1.000000
                                max    120158.000000   491.000000   2.000000
Voice                           count      11.000000    11.000000  11.000000
                                mean   120108.000000    27.636364   0.000000
                                std        33.166248     5.162804   0.000000
                                min    120058.000000    19.000000   0.000000
                                25%    120083.000000    24.500000   0.000000
                                50%    120108.000000    28.000000   0.000000
                                75%    120133.000000    31.000000   0.000000
                                max    120158.000000    35.000000   0.000000

[1952 rows x 9 columns]

In [9]:
df_cs = group_majors.get_group("Advertising")

KeyError: 'Advertising'

In [10]:
df_cs = group_majors.get_group("Advertising ")

In [11]:
df_cs

,% Female,Academic Program Code,College,Conc. Code,Conc. Name,Degree,Dept.,Fall,Female,Major Code,Male,Term Code,Total,Unknown
134,0.851852,10KS0277MS,KT,,,MS,408.0,2015.0,23.0,277.0,4.0,120158.0,27.0,0.0
135,0.676157,10KT0277BS,KT,,,BS,408.0,2015.0,380.0,277.0,182.0,120158.0,562.0,0.0
829,0.833333,10KS0277MS,KT,,,MS,408.0,2014.0,20.0,277.0,4.0,120148.0,24.0,0.0
830,0.692573,10KT0277BS,KT,,,BS,408.0,2014.0,401.0,277.0,178.0,120148.0,579.0,0.0
1510,0.750000,10KS0277MS,KT,,,MS,408.0,2013.0,27.0,277.0,9.0,120138.0,36.0,0.0
1511,0.720207,10KT0277BS,KT,,,BS,408.0,2013.0,417.0,277.0,162.0,120138.0,579.0,0.0
2213,0.710526,10KS0277MS,KT,,,MS,408.0,2012.0,27.0,277.0,11.0,120128.0,38.0,0.0
2214,0.719735,10KT0277BS,KT,,,BS,408.0,2012.0,434.0,277.0,169.0,120128.0,603.0,0.0
2906,0.766667,10KS0277MS,KT,,,MS,408.0,2011.0,23.0,277.0,7.0,120118.0,30.0,0.0
2907,0.691693,10KT0277BS,KT,,,BS,408.0,2011.0,433.0,277.0,193.0,120118.0,626.0,0.0
3607,1.000000,10KS0277MS,KT,,,MS,408.0,2010.0,15.0,277.0,0.0,120108.0,15.0,0.0
3608,0.690802,10KT0277BS,KT,,,BS,408.0,2010.0,353.0,277.0,158.0,120108.0,511.0,0.0
4300,0.750000,10KS0277MS,KT,,,MS,408.0,2009.0,12.0,277.0,4.0,120098.0,16.0,0.0
4301,0.664319,10KT0277BS,KT,,,BS,408.0,2009.0,283.0,277.0,142.0,120098.0,426.0,1.0
4967,0.777778,10KS0277MS,KT,,,MS,408.0,2008.0,21.0,277.0,6.0,120088.0,27.0,0.0
4968,0.704388,10KT0277BS,KT,,,BS,408.0,2008.0,305.0,277.0,128.0,120088.0,433.0,0.0
5595,0.700000,10KS0277MS,KT,,,MS,408.0,2007.0,21.0,277.0,9.0,120078.0,30.0,0.0
5596,0.747191,10KT0277BS,KT,,,BS,408.0,2007.0,266.0,277.0,90.0,120078.0,356.0,0.0
6205,0.703704,10KS0277MS,KT,,,MS,408.0,2006.0,19.0,277.0,8.0,120068.0,27.0,0.0
6206,0.733728,10KT0277BS,KT,,,BS,408.0,2006.0,248.0,277.0,90.0,120068.0,338.0,0.0
6822,0.714286,10KS0277MS,KT,,,MS,408.0,2005.0,20.0,277.0,8.0,120058.0,28.0,0.0
6823,0.748936,10KT0277BS,KT,,,BS,408.0,2005.0,176.0,277.0,59.0,120058.0,235.0,0.0

In [20]:
df_cs = df_cs[ df_cs["Degree"] == "BS "]
df_cs = df_cs[ df_cs["Fall"] == 2015.0 ]

,% Female,Academic Program Code,College,Conc. Code,Conc. Name,Degree,Dept.,Fall,Female,Major Code,Male,Term Code,Total,Unknown
135,0.676157,10KT0277BS,KT,,,BS,408.0,2015.0,380.0,277.0,182.0,120158.0,562.0,0.0

In [23]:
df_cs = group_majors.get_group("Advertising ")
df_cs = df_cs[ df_cs["Degree"] == "BS "]
g2 = df_cs.groupby("Fall")
g2.sum()

        % Female  Dept.  Female  Major Code   Male  Term Code  Total  Unknown
Fall
2005.0  0.748936  408.0   176.0       277.0   59.0   120058.0  235.0      0.0
2006.0  0.733728  408.0   248.0       277.0   90.0   120068.0  338.0      0.0
2007.0  0.747191  408.0   266.0       277.0   90.0   120078.0  356.0      0.0
2008.0  0.704388  408.0   305.0       277.0  128.0   120088.0  433.0      0.0
2009.0  0.664319  408.0   283.0       277.0  142.0   120098.0  426.0      1.0
2010.0  0.690802  408.0   353.0       277.0  158.0   120108.0  511.0      0.0
2011.0  0.691693  408.0   433.0       277.0  193.0   120118.0  626.0      0.0
2012.0  0.719735  408.0   434.0       277.0  169.0   120128.0  603.0      0.0
2013.0  0.720207  408.0   417.0       277.0  162.0   120138.0  579.0      0.0
2014.0  0.692573  408.0   401.0       277.0  178.0   120148.0  579.0      0.0
2015.0  0.676157  408.0   380.0       277.0  182.0   120158.0  562.0      0.0